version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin
    ports:
      - "5434:5432"
    volumes:
      - product_db_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-net

volumes:
  product_db_data:

networks:
  ecommerce-net:
    external: true